# Dockerfile.metasploitable2
# On dérive de l’image communautaire la plus proche
FROM tleemcjr/metasploitable2:latest

# On expose explicitement les services vulnérables mis en avant dans le TP
EXPOSE 21 22 80 445 5432
CMD ["/bin/bash"]