flowchart TD
    A([Start]) -->|Launch Scan| B([IP Scan])
    B -->|-1| C([Port Scan])
    B --> D{Choose Attack Type}
    C --> D

    %% Attack part
    D -->|-1| E1([FTP Brute Force])
    D -->|-1| E2([SSH Brute Force])
    D -->|-1| E3([VSFTPD Exploit])

    E1 -->|+10| G1(<b>Success</b>)
    E2 -->|+10| G1
    E3 -->|+10| G1
    E1 -->|-10| G2(<b>Fail</b>)
    E2 -->|-10| G2
    E3 -->|-10| G2

    %% Coloring the nodes
    style B fill:#FFA500,color:#000000,stroke:#333,stroke-width:2px
    style C fill:#FFA500,color:#000000,stroke:#333,stroke-width:2px
    style D fill:#2485e1,color:#000000,stroke:#333,stroke-width:2px
    style G1 fill:#00FF00,color:#000000,stroke:#333,stroke-width:2px
    style G2 fill:#FF0000,color:#000000,stroke:#333,stroke-width:2px